[tool.poetry]
name = "ib-isn"
version = "0.0.1"
description = "Interactome based Individual Specific Networks"
authors = ["Giada Lalli <giada.lalli@kuleuven.be>",
           "VIB Bioinformatics Core Facility <bits@vib.be>"]
readme = "README.md"
packages = [{include = "ib_isn"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
pandas = "^1.5.2"
numpy = "^1.24.1"
scipy = "^1.10.0"
scikit-learn = "^1.2.0"
torch = "^1.13.1"
scikit-allel = "^1.3.5"


[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pylint = "^2.15.10"
pytest = "^7.2.0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
