on:
  pull_request:
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v8

      - name: PyLint
        run: poetry run pylist ib_isn/

      - name: Code formatting
        run: poetry run black --check .

      - name: Type checking
        run: poetry run mypy ib_isn/
