on:
  pull_request:
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install

      - name: PyLint
        run: poetry run pylint isn_tractor/

      - name: Code formatting
        run: poetry run black --check .

      - name: Type checking
        run: poetry run mypy isn_tractor/

      - name: Tests
        run: poetry run pytest --junitxml=report.xml --cov=isn_tractor/ --cov-fail-under=45

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests on Python ${{ matrix.python-version }}
          path: report.xml
          reporter: java-junit
